rl_params:
  algorithm: ppo
  epsilon: 0.1
  entropy_coef: 0.08
  n_epochs_before_resample: 10
  kl_threshold: 0.03

optimizer_specs:
  optimizer: adam
  learning_rate: 1.0e-4

training_specs:
  batch_size: 512
  n_seq_per_iter: 500 # for debug
  n_iters: 50 # for debug
#  start_iter : 38
  prior_diff_coef: 0 
  prior_model: /global/scratch/users/ozhang/covid/rl_dataset/dahai_frag_pretrained.pkl  
  starting_policy_model: /global/scratch/users/ozhang/covid/rl_dataset/dahai_frag_pretrained.pkl  
  grammar: /global/scratch/users/ozhang/covid/rl_dataset/frag_grammar.txt
#  model_weights: /global/scratch/users/ozhang/covid/ZikvPro/open_update/models/model_20

rewards:
#  - type: docking
#    weight: 2
#    params:
#      protein_file: /global/scratch/users/ozhang/covid/rdkit_vina/ns3_protease.pdbqt
#      box:  [-21, 5.5, -24, -3, 22.5, 0] # [47, 64, 12, 65, 82, 35]
#      protocols: ["vina_gpu", "rfscore"]
#      timeout: 60
#      fragment: ["Cc2cc(N)c1cccc(Cl)c1n2", [-13.79580109,  15.63052044, -17.64702725]]
#  - type: interaction # need to be listed right after vina
#    weight: 1
#    params:
#      protein_path: /global/scratch/users/ozhang/covid/ZikvPro/ns3_protease.pdb
      # interaction types supported: hydrogen_bond, hydrophobic_interaction, pi_stack, salt_bridge, halogen_bond
#      key_residues: ["SER/81/A", "ASP/83/A", "ASP/75/B", "HIS/51/B", "GLY/151/B", "GLY/153/B",
#                   "SER/135/B", "TYR/161/B", "TYR/130/B", "ASP/129/B", "VAL/154/B"]
  - type: fragment_similarity
    weight: 8
    params:
      fragments: ['CNc1cc(C)nc2c(Cl)cccc12']
      weights: [1]
      global_substructure_match: True
  - type: drug_likeliness
    weight: 1
#  - type: solubility
#    weight: 1

run:
  random_seed: 42
  output_dir: /global/scratch/users/ozhang/covid/ZikvPro/test_frag

#mpro macrocycle CCCC(NC(=O)c3cccc4nc(c1cncc2ccccc12)n(CCCCC(=O)NC)c34)c5ccc(C(F)(F)F)cc5