name: iMiner python tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          source $CONDA/bin/activate
          conda create -n iminer python=${{ matrix.python-version }} numpy pandas acpype pytest pytest-xdist rdkit tqdm -c conda-forge
      - name: Install iMiner
        run: |
          source $CONDA/bin/activate iminer
          python setup.py install
      - name: Run Tests
        run: |
          source $CONDA/bin/activate iminer
          pytest -vs tests/  
